name: Build BitChat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      
    - name: Build for macOS
      run: |
        xcodebuild -project bitchat.xcodeproj \
        -scheme "bitchat_macOS" \
        -configuration Debug \
        -destination 'platform=macOS' \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        build

  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      
    - name: Build for iOS
      run: |
        xcodebuild -project bitchat.xcodeproj \
        -scheme "bitchat_iOS" \
        -configuration Debug \
        -destination 'platform=iOS Simulator,name=iPhone 15' \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        build